ALTER TABLE TRANSPORTATION_AUTHORITY
RENAME COLUMN AUTHORITY_NAME TO authorityName;

ALTER TABLE TRANSPORTATION_AUTHORITY
RENAME COLUMN CONTACT_INFORMATION TO contactInformation;

ALTER TABLE SECURITY_PERSONNEL
RENAME COLUMN CONTACT_PERSON TO contactPerson;

ALTER TABLE SECURITY_AGENCY
RENAME COLUMN AGENCY_NAME TO agencyName;

ALTER TABLE SECURITY_AGENCY
RENAME COLUMN AGENCY_TYPE TO agencyType;

ALTER TABLE SECURITY_AGENCY
RENAME COLUMN CONTACT_PERSON TO contactPerson;

ALTER TABLE PERFORMANCE_DETAILS
RENAME COLUMN STRENGTH_GAINS TO strengthGains;

ALTER TABLE PARTS_OF
RENAME COLUMN EDITION_ID TO editionID;

ALTER TABLE PARTS_OF
RENAME COLUMN COUNTRY_ID TO countryID;

ALTER TABLE ORGANIZERS
RENAME COLUMN ORGANIZERS_NAME TO organizersName;

ALTER TABLE OLMPICS_VILLAGE
RENAME COLUMN VILLAGE_ID TO villageID;

ALTER TABLE OLMPICS_VILLAGE
RENAME COLUMN VILLAGE_NAME TO villageName;

ALTER TABLE NATIONAL_ANTHEM
RENAME COLUMN COUNTRY_ID TO countryID;

ALTER TABLE NATIONAL_ANTHEM
RENAME COLUMN VILLAGE_ID TO villageID;

ALTER TABLE MEDALS
RENAME COLUMN MEDAL_TYPE TO medalType;

ALTER TABLE MEDALS
RENAME COLUMN DATE_AWARDED TO dateAwarded;

ALTER TABLE INDULGES_IN
RENAME COLUMN DOPING_RESULTID TO dopingResultID;

ALTER TABLE DOPING_RESULTS
RENAME COLUMN APPEAL_STATUS TO appealStatus;


ALTER TABLE DOPING_RESULTS
RENAME COLUMN DOPING_STATUS TO dopingStatus;


ALTER TABLE DOPING_RESULTS
RENAME COLUMN TESTING_AUTHORITY TO testingAuthority;

ALTER TABLE COUNTRY
RENAME COLUMN COUNTRY_ID TO countryID;

ALTER TABLE COUNTRY
RENAME COLUMN COUNTRY_NAME TO countryName;

ALTER TABLE COACH
RENAME COLUMN COACH_NAME TO coachName;

ALTER TABLE TICKET_SALE
MODIFY purchasePrice NUMBER(10,2);



commit;