CREATE TABLE AUDIT_LOG (
  operation_type VARCHAR2(10) NOT NULL,
  table_name VARCHAR2(30) NOT NULL,
  column_name VARCHAR2(30) NOT NULL,
  old_value VARCHAR2(255),
  new_value VARCHAR2(255),
  date_changed TIMESTAMP NOT NULL
);

DROP table AUDIT_LOG;

SELECT * FROM EVENTS;
SELECT * FROM TICKET_CATEGORY;
SELECT * FROM TICKET_SALE;
SELECT * FROM EVENTS;
